# Enable mouse mode
set -g mouse on

# Set prefix to Ctrl-x
unbind C-b
set -g prefix C-x
bind C-x send-prefix

# Set shell to Fish with proper initialization
set -g default-shell /opt/homebrew/bin/fish
set -g default-command "exec /opt/homebrew/bin/fish -l"
set -g default-terminal "screen-256color"

# Enable focus events
set -g focus-events on

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
