# Completions for jenkins CLI wrapper
complete -c jenkins -f

# Jenkins CLI commands
complete -c jenkins -n __fish_use_subcommand -a add-job-to-view -d "Add jobs to view"
complete -c jenkins -n __fish_use_subcommand -a build -d "Build a job"
complete -c jenkins -n __fish_use_subcommand -a cancel-quiet-down -d "Cancel quiet-down"
complete -c jenkins -n __fish_use_subcommand -a clear-queue -d "Clear build queue"
complete -c jenkins -n __fish_use_subcommand -a connect-node -d "Reconnect to node(s)"
complete -c jenkins -n __fish_use_subcommand -a console -d "Get console output of a build"
complete -c jenkins -n __fish_use_subcommand -a copy-job -d "Copy a job"
complete -c jenkins -n __fish_use_subcommand -a create-job -d "Create a new job from XML"
complete -c jenkins -n __fish_use_subcommand -a create-node -d "Create a new node from XML"
complete -c jenkins -n __fish_use_subcommand -a create-view -d "Create a new view from XML"
complete -c jenkins -n __fish_use_subcommand -a declarative-linter -d "Validate Declarative Jenkinsfile"
complete -c jenkins -n __fish_use_subcommand -a delete-builds -d "Delete build record(s)"
complete -c jenkins -n __fish_use_subcommand -a delete-job -d "Delete job(s)"
complete -c jenkins -n __fish_use_subcommand -a delete-node -d "Delete node(s)"
complete -c jenkins -n __fish_use_subcommand -a delete-view -d "Delete view(s)"
complete -c jenkins -n __fish_use_subcommand -a disable-job -d "Disable a job"
complete -c jenkins -n __fish_use_subcommand -a disable-plugin -d "Disable installed plugins"
complete -c jenkins -n __fish_use_subcommand -a disconnect-node -d "Disconnect from a node"
complete -c jenkins -n __fish_use_subcommand -a enable-job -d "Enable a job"
complete -c jenkins -n __fish_use_subcommand -a enable-plugin -d "Enable installed plugins"
complete -c jenkins -n __fish_use_subcommand -a get-job -d "Dump job definition XML"
complete -c jenkins -n __fish_use_subcommand -a get-node -d "Dump node definition XML"
complete -c jenkins -n __fish_use_subcommand -a get-view -d "Dump view definition XML"
complete -c jenkins -n __fish_use_subcommand -a groovy -d "Execute Groovy script"
complete -c jenkins -n __fish_use_subcommand -a groovysh -d "Interactive Groovy shell"
complete -c jenkins -n __fish_use_subcommand -a help -d "List available commands"
complete -c jenkins -n __fish_use_subcommand -a install-plugin -d "Install a plugin"
complete -c jenkins -n __fish_use_subcommand -a keep-build -d "Mark build to keep forever"
complete -c jenkins -n __fish_use_subcommand -a list-changes -d "Dump changelog for build(s)"
complete -c jenkins -n __fish_use_subcommand -a list-credentials -d "List credentials in a store"
complete -c jenkins -n __fish_use_subcommand -a list-jobs -d "List all jobs"
complete -c jenkins -n __fish_use_subcommand -a list-plugins -d "List installed plugins"
complete -c jenkins -n __fish_use_subcommand -a offline-node -d "Take node offline"
complete -c jenkins -n __fish_use_subcommand -a online-node -d "Bring node online"
complete -c jenkins -n __fish_use_subcommand -a quiet-down -d "Quiet down Jenkins"
complete -c jenkins -n __fish_use_subcommand -a reload-configuration -d "Reload config from disk"
complete -c jenkins -n __fish_use_subcommand -a reload-job -d "Reload job(s)"
complete -c jenkins -n __fish_use_subcommand -a remove-job-from-view -d "Remove jobs from view"
complete -c jenkins -n __fish_use_subcommand -a replay-pipeline -d "Replay Pipeline build"
complete -c jenkins -n __fish_use_subcommand -a restart -d "Restart Jenkins"
complete -c jenkins -n __fish_use_subcommand -a restart-from-stage -d "Restart from a stage"
complete -c jenkins -n __fish_use_subcommand -a safe-restart -d "Safe restart Jenkins"
complete -c jenkins -n __fish_use_subcommand -a safe-shutdown -d "Safe shutdown Jenkins"
complete -c jenkins -n __fish_use_subcommand -a session-id -d "Output session ID"
complete -c jenkins -n __fish_use_subcommand -a set-build-description -d "Set build description"
complete -c jenkins -n __fish_use_subcommand -a set-build-display-name -d "Set build display name"
complete -c jenkins -n __fish_use_subcommand -a shutdown -d "Shutdown Jenkins"
complete -c jenkins -n __fish_use_subcommand -a stop-builds -d "Stop running builds"
complete -c jenkins -n __fish_use_subcommand -a update-job -d "Update job definition from XML"
complete -c jenkins -n __fish_use_subcommand -a update-node -d "Update node definition from XML"
complete -c jenkins -n __fish_use_subcommand -a update-view -d "Update view definition from XML"
complete -c jenkins -n __fish_use_subcommand -a version -d "Show Jenkins version"
complete -c jenkins -n __fish_use_subcommand -a wait-node-offline -d "Wait for node offline"
complete -c jenkins -n __fish_use_subcommand -a wait-node-online -d "Wait for node online"
complete -c jenkins -n __fish_use_subcommand -a who-am-i -d "Check credentials and permissions"

# Meta-commands (wrapper-specific)
complete -c jenkins -n __fish_use_subcommand -a update -d "Re-download jenkins-cli.jar"
complete -c jenkins -n __fish_use_subcommand -a doctor -d "Check prerequisites"
complete -c jenkins -n __fish_use_subcommand -a setup -d "Configure authentication"
