# fzf-lua CLI keybindings help

function _fzf_lua_keybindings_help --description "Show fzf-lua CLI keybindings help"
    echo ""
    echo "╔══════════════════════════════════════════════════════════════════╗"
    echo "║          fzf-lua CLI Keybindings (Press ESC first)               ║"
    echo "╠══════════════════════════════════════════════════════════════════╣"
    echo "║  PICKERS (Space + key)                                           ║"
    echo "║    <Space>ff   Find files              <Space>fg   Live grep     ║"
    echo "║    <Space>fF   Find files (home)       <Space>fr   Recent files  ║"
    echo "║    <Space>cd   Zoxide directories      <Space>fR   Recent (all)  ║"
    echo "║    <Space>fz   All pickers                                       ║"
    echo "╠══════════════════════════════════════════════════════════════════╣"
    echo "║  GIT PICKERS                                                     ║"
    echo "║    <Space>gs   Git status              <Space>gl   Git log       ║"
    echo "║    <Space>gf   Git files               <Space>gb   Git branches  ║"
    echo "╠══════════════════════════════════════════════════════════════════╣"
    echo "║  INSIDE PICKER                                                   ║"
    echo "║    Tab/S-Tab   Multi-select            Ctrl-/      Toggle preview║"
    echo "║    Alt-L       Local scope             Ctrl-Y      Copy path     ║"
    echo "║    Alt-S       Git root scope          Enter       Open/Select   ║"
    echo "║    Alt-G       Global (home) scope     Esc         Cancel        ║"
    echo "║    Alt-P       Parent directory scope                            ║"
    echo "╚══════════════════════════════════════════════════════════════════╝"
    echo ""
end
