# fzf-lua CLI keybindings help

function _fzf_lua_keybindings_help --description "Show fzf-lua CLI keybindings help"
    echo ""
    echo "╔══════════════════════════════════════════════════════════════════╗"
    echo "║     fzf-lua CLI Keybindings (Space Leader in Normal Mode)        ║"
    echo "║                    Press ESC first, then:                        ║"
    echo "╠══════════════════════════════════════════════════════════════════╣"
    echo "║  FILE PICKERS (<Space>f prefix)                                  ║"
    echo "║    <Space>ff   Find files → open in nvim                         ║"
    echo "║    <Space>fF   Find files from home → open in nvim               ║"
    echo "║    <Space>cd   Zoxide directories → cd to dir                    ║"
    echo "║    <Space>fg   Live grep → open in nvim                          ║"
    echo "║    <Space>fr   Recent files (local) → open in nvim               ║"
    echo "║    <Space>fR   Recent files (global) → open in nvim              ║"
    echo "║    <Space>fz   All pickers (builtin)                             ║"
    echo "╠══════════════════════════════════════════════════════════════════╣"
    echo "║  GIT PICKERS (<Space>g prefix)                                   ║"
    echo "║    <Space>gs   Git status → open in nvim                         ║"
    echo "║    <Space>gf   Git files → open in nvim                          ║"
    echo "║    <Space>gl   Git commits (log)                                 ║"
    echo "║    <Space>gb   Git branches                                      ║"
    echo "╠══════════════════════════════════════════════════════════════════╣"
    echo "║  INSIDE PICKER                                                   ║"
    echo "║    Ctrl-D      Switch to Local scope (current dir)               ║"
    echo "║    Ctrl-S      Switch to Git Root scope                          ║"
    echo "║    Ctrl-G      Switch to Global scope (home dir)                 ║"
    echo "╚══════════════════════════════════════════════════════════════════╝"
    echo ""
end
