// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddToQueue(arg1:string,arg2:string,arg3:string,arg4:number):Promise<void>;

export function CloseTerminal(arg1:string):Promise<void>;

export function CreateTerminal(arg1:string,arg2:string):Promise<string>;

export function CreateWorkspace(arg1:string,arg2:boolean):Promise<main.WorkspaceInfo>;

export function GetWSPort():Promise<number>;

export function KillWorkspace(arg1:string,arg2:boolean):Promise<void>;

export function ListQueue():Promise<Array<main.QueueEntry>>;

export function ListWorkspaces():Promise<Array<main.WorkspaceInfo>>;

export function RemoveFromQueue(arg1:string):Promise<void>;

export function ResizeTerminal(arg1:string,arg2:number,arg3:number):Promise<void>;

export function RunTicket(arg1:string,arg2:string,arg3:string):Promise<main.WorkspaceInfo>;
