// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddToQueue(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['AddToQueue'](arg1, arg2, arg3, arg4);
}

export function CloseTerminal(arg1) {
  return window['go']['main']['App']['CloseTerminal'](arg1);
}

export function CreateTerminal(arg1, arg2) {
  return window['go']['main']['App']['CreateTerminal'](arg1, arg2);
}

export function CreateWorkspace(arg1, arg2) {
  return window['go']['main']['App']['CreateWorkspace'](arg1, arg2);
}

export function GetWSPort() {
  return window['go']['main']['App']['GetWSPort']();
}

export function KillWorkspace(arg1, arg2) {
  return window['go']['main']['App']['KillWorkspace'](arg1, arg2);
}

export function ListQueue() {
  return window['go']['main']['App']['ListQueue']();
}

export function ListWorkspaces() {
  return window['go']['main']['App']['ListWorkspaces']();
}

export function RemoveFromQueue(arg1) {
  return window['go']['main']['App']['RemoveFromQueue'](arg1);
}

export function ResizeTerminal(arg1, arg2, arg3) {
  return window['go']['main']['App']['ResizeTerminal'](arg1, arg2, arg3);
}

export function RunTicket(arg1, arg2, arg3) {
  return window['go']['main']['App']['RunTicket'](arg1, arg2, arg3);
}
