# kubectl-abbr-setup.fish - One-time setup for kubectl abbreviations as universal variables
# Run this once with: fish -c "source ~/.config/fish/setup/kubectl-abbr-setup.fish"
#
# This converts kubectl abbreviations to Fish universal variables.
# Universal variables persist across sessions, eliminating the need to define
# 768 abbreviations on every shell startup.
#
# Expected improvement: 100-200ms startup time reduction

if set -q _kubectl_abbr_installed
    echo "Kubectl abbreviations already installed as universal variables."
    echo "To reinstall, first run: set -eU _kubectl_abbr_installed"
    return 0
end

echo "Installing 768 kubectl abbreviations as universal variables..."
echo "This only needs to be done once."

# kubectl abbreviations (converted from conf.d/kubectl-aliases.fish)
abbr -a k "kubectl"
abbr -a ksys "kubectl --namespace=kube-system"
abbr -a ka "kubectl apply --recursive -f"
abbr -a ksysa "kubectl --namespace=kube-system apply --recursive -f"
abbr -a kak "kubectl apply -k"
abbr -a kk "kubectl kustomize"
abbr -a kex "kubectl exec -i -t"
abbr -a ksysex "kubectl --namespace=kube-system exec -i -t"
abbr -a klo "kubectl logs -f"
abbr -a ksyslo "kubectl --namespace=kube-system logs -f"
abbr -a klop "kubectl logs -f -p"
abbr -a ksyslop "kubectl --namespace=kube-system logs -f -p"
abbr -a kp "kubectl proxy"
abbr -a kpf "kubectl port-forward"
abbr -a kg "kubectl get"
abbr -a ksysg "kubectl --namespace=kube-system get"
abbr -a kd "kubectl describe"
abbr -a ksysd "kubectl --namespace=kube-system describe"
abbr -a krm "kubectl delete"
abbr -a ksysrm "kubectl --namespace=kube-system delete"
abbr -a krun "kubectl run --rm --restart=Never --image-pull-policy=IfNotPresent -i -t"
abbr -a ksysrun "kubectl --namespace=kube-system run --rm --restart=Never --image-pull-policy=IfNotPresent -i -t"
abbr -a kgpo "kubectl get pods"
abbr -a ksysgpo "kubectl --namespace=kube-system get pods"
abbr -a kdpo "kubectl describe pods"
abbr -a ksysdpo "kubectl --namespace=kube-system describe pods"
abbr -a krmpo "kubectl delete pods"
abbr -a ksysrmpo "kubectl --namespace=kube-system delete pods"
abbr -a kgdep "kubectl get deployment"
abbr -a ksysgdep "kubectl --namespace=kube-system get deployment"
abbr -a kddep "kubectl describe deployment"
abbr -a ksysddep "kubectl --namespace=kube-system describe deployment"
abbr -a krmdep "kubectl delete deployment"
abbr -a ksysrmdep "kubectl --namespace=kube-system delete deployment"
abbr -a kgsts "kubectl get statefulset"
abbr -a ksysgsts "kubectl --namespace=kube-system get statefulset"
abbr -a kdsts "kubectl describe statefulset"
abbr -a ksysdsts "kubectl --namespace=kube-system describe statefulset"
abbr -a krmsts "kubectl delete statefulset"
abbr -a ksysrmsts "kubectl --namespace=kube-system delete statefulset"
abbr -a kgsvc "kubectl get service"
abbr -a ksysgsvc "kubectl --namespace=kube-system get service"
abbr -a kdsvc "kubectl describe service"
abbr -a ksysdsvc "kubectl --namespace=kube-system describe service"
abbr -a krmsvc "kubectl delete service"
abbr -a ksysrmsvc "kubectl --namespace=kube-system delete service"
abbr -a kging "kubectl get ingress"
abbr -a ksysging "kubectl --namespace=kube-system get ingress"
abbr -a kding "kubectl describe ingress"
abbr -a ksysding "kubectl --namespace=kube-system describe ingress"
abbr -a krming "kubectl delete ingress"
abbr -a ksysrming "kubectl --namespace=kube-system delete ingress"
abbr -a kgcm "kubectl get configmap"
abbr -a ksysgcm "kubectl --namespace=kube-system get configmap"
abbr -a kdcm "kubectl describe configmap"
abbr -a ksysdcm "kubectl --namespace=kube-system describe configmap"
abbr -a krmcm "kubectl delete configmap"
abbr -a ksysrmcm "kubectl --namespace=kube-system delete configmap"
abbr -a kgsec "kubectl get secret"
abbr -a ksysgsec "kubectl --namespace=kube-system get secret"
abbr -a kdsec "kubectl describe secret"
abbr -a ksysdsec "kubectl --namespace=kube-system describe secret"
abbr -a krmsec "kubectl delete secret"
abbr -a ksysrmsec "kubectl --namespace=kube-system delete secret"
abbr -a kgno "kubectl get nodes"
abbr -a kdno "kubectl describe nodes"
abbr -a kgns "kubectl get namespaces"
abbr -a kdns "kubectl describe namespaces"
abbr -a krmns "kubectl delete namespaces"
abbr -a kgoyaml "kubectl get -o=yaml"
abbr -a ksysgoyaml "kubectl --namespace=kube-system get -o=yaml"
abbr -a kgpooyaml "kubectl get pods -o=yaml"
abbr -a ksysgpooyaml "kubectl --namespace=kube-system get pods -o=yaml"
abbr -a kgdepoyaml "kubectl get deployment -o=yaml"
abbr -a ksysgdepoyaml "kubectl --namespace=kube-system get deployment -o=yaml"
abbr -a kgstsoyaml "kubectl get statefulset -o=yaml"
abbr -a ksysgstsoyaml "kubectl --namespace=kube-system get statefulset -o=yaml"
abbr -a kgsvcoyaml "kubectl get service -o=yaml"
abbr -a ksysgsvcoyaml "kubectl --namespace=kube-system get service -o=yaml"
abbr -a kgingoyaml "kubectl get ingress -o=yaml"
abbr -a ksysgingoyaml "kubectl --namespace=kube-system get ingress -o=yaml"
abbr -a kgcmoyaml "kubectl get configmap -o=yaml"
abbr -a ksysgcmoyaml "kubectl --namespace=kube-system get configmap -o=yaml"
abbr -a kgsecoyaml "kubectl get secret -o=yaml"
abbr -a ksysgsecoyaml "kubectl --namespace=kube-system get secret -o=yaml"
abbr -a kgnooyaml "kubectl get nodes -o=yaml"
abbr -a kgnsoyaml "kubectl get namespaces -o=yaml"
abbr -a kgowide "kubectl get -o=wide"
abbr -a ksysgowide "kubectl --namespace=kube-system get -o=wide"
abbr -a kgpoowide "kubectl get pods -o=wide"
abbr -a ksysgpoowide "kubectl --namespace=kube-system get pods -o=wide"
abbr -a kgdepowide "kubectl get deployment -o=wide"
abbr -a ksysgdepowide "kubectl --namespace=kube-system get deployment -o=wide"
abbr -a kgstsowide "kubectl get statefulset -o=wide"
abbr -a ksysgstsowide "kubectl --namespace=kube-system get statefulset -o=wide"
abbr -a kgsvcowide "kubectl get service -o=wide"
abbr -a ksysgsvcowide "kubectl --namespace=kube-system get service -o=wide"
abbr -a kgingowide "kubectl get ingress -o=wide"
abbr -a ksysgingowide "kubectl --namespace=kube-system get ingress -o=wide"
abbr -a kgcmowide "kubectl get configmap -o=wide"
abbr -a ksysgcmowide "kubectl --namespace=kube-system get configmap -o=wide"
abbr -a kgsecowide "kubectl get secret -o=wide"
abbr -a ksysgsecowide "kubectl --namespace=kube-system get secret -o=wide"
abbr -a kgnoowide "kubectl get nodes -o=wide"
abbr -a kgnsowide "kubectl get namespaces -o=wide"
abbr -a kgojson "kubectl get -o=json"
abbr -a ksysgojson "kubectl --namespace=kube-system get -o=json"
abbr -a kgpoojson "kubectl get pods -o=json"
abbr -a ksysgpoojson "kubectl --namespace=kube-system get pods -o=json"
abbr -a kgdepojson "kubectl get deployment -o=json"
abbr -a ksysgdepojson "kubectl --namespace=kube-system get deployment -o=json"
abbr -a kgstsojson "kubectl get statefulset -o=json"
abbr -a ksysgstsojson "kubectl --namespace=kube-system get statefulset -o=json"
abbr -a kgsvcojson "kubectl get service -o=json"
abbr -a ksysgsvcojson "kubectl --namespace=kube-system get service -o=json"
abbr -a kgingojson "kubectl get ingress -o=json"
abbr -a ksysgingojson "kubectl --namespace=kube-system get ingress -o=json"
abbr -a kgcmojson "kubectl get configmap -o=json"
abbr -a ksysgcmojson "kubectl --namespace=kube-system get configmap -o=json"
abbr -a kgsecojson "kubectl get secret -o=json"
abbr -a ksysgsecojson "kubectl --namespace=kube-system get secret -o=json"
abbr -a kgnoojson "kubectl get nodes -o=json"
abbr -a kgnsojson "kubectl get namespaces -o=json"
abbr -a kgall "kubectl get --all-namespaces"
abbr -a kdall "kubectl describe --all-namespaces"
abbr -a kgpoall "kubectl get pods --all-namespaces"
abbr -a kdpoall "kubectl describe pods --all-namespaces"
abbr -a kgdepall "kubectl get deployment --all-namespaces"
abbr -a kddepall "kubectl describe deployment --all-namespaces"
abbr -a kgstsall "kubectl get statefulset --all-namespaces"
abbr -a kdstsall "kubectl describe statefulset --all-namespaces"
abbr -a kgsvcall "kubectl get service --all-namespaces"
abbr -a kdsvcall "kubectl describe service --all-namespaces"
abbr -a kgingall "kubectl get ingress --all-namespaces"
abbr -a kdingall "kubectl describe ingress --all-namespaces"
abbr -a kgcmall "kubectl get configmap --all-namespaces"
abbr -a kdcmall "kubectl describe configmap --all-namespaces"
abbr -a kgsecall "kubectl get secret --all-namespaces"
abbr -a kdsecall "kubectl describe secret --all-namespaces"
abbr -a kgnsall "kubectl get namespaces --all-namespaces"
abbr -a kdnsall "kubectl describe namespaces --all-namespaces"
abbr -a kgsl "kubectl get --show-labels"
abbr -a ksysgsl "kubectl --namespace=kube-system get --show-labels"
abbr -a kgposl "kubectl get pods --show-labels"
abbr -a ksysgposl "kubectl --namespace=kube-system get pods --show-labels"
abbr -a kgdepsl "kubectl get deployment --show-labels"
abbr -a ksysgdepsl "kubectl --namespace=kube-system get deployment --show-labels"
abbr -a kgw "kubectl get --watch"
abbr -a ksysgw "kubectl --namespace=kube-system get --watch"
abbr -a kgpow "kubectl get pods --watch"
abbr -a ksysgpow "kubectl --namespace=kube-system get pods --watch"
abbr -a kgdepw "kubectl get deployment --watch"
abbr -a ksysgdepw "kubectl --namespace=kube-system get deployment --watch"
abbr -a kgstsw "kubectl get statefulset --watch"
abbr -a ksysgstsw "kubectl --namespace=kube-system get statefulset --watch"
abbr -a kgsvcw "kubectl get service --watch"
abbr -a ksysgsvcw "kubectl --namespace=kube-system get service --watch"
abbr -a kgingw "kubectl get ingress --watch"
abbr -a ksysgingw "kubectl --namespace=kube-system get ingress --watch"
abbr -a kgcmw "kubectl get configmap --watch"
abbr -a ksysgcmw "kubectl --namespace=kube-system get configmap --watch"
abbr -a kgsecw "kubectl get secret --watch"
abbr -a ksysgsecw "kubectl --namespace=kube-system get secret --watch"
abbr -a kgnow "kubectl get nodes --watch"
abbr -a kgnsw "kubectl get namespaces --watch"
abbr -a kgoyamlall "kubectl get -o=yaml --all-namespaces"
abbr -a kgpooyamlall "kubectl get pods -o=yaml --all-namespaces"
abbr -a kgdepoyamlall "kubectl get deployment -o=yaml --all-namespaces"
abbr -a kgstsoyamlall "kubectl get statefulset -o=yaml --all-namespaces"
abbr -a kgsvcoyamlall "kubectl get service -o=yaml --all-namespaces"
abbr -a kgingoyamlall "kubectl get ingress -o=yaml --all-namespaces"
abbr -a kgcmoyamlall "kubectl get configmap -o=yaml --all-namespaces"
abbr -a kgsecoyamlall "kubectl get secret -o=yaml --all-namespaces"
abbr -a kgnsoyamlall "kubectl get namespaces -o=yaml --all-namespaces"
abbr -a kgowideall "kubectl get -o=wide --all-namespaces"
abbr -a kgpoowideall "kubectl get pods -o=wide --all-namespaces"
abbr -a kgdepowideall "kubectl get deployment -o=wide --all-namespaces"
abbr -a kgstsowideall "kubectl get statefulset -o=wide --all-namespaces"
abbr -a kgsvcowideall "kubectl get service -o=wide --all-namespaces"
abbr -a kgingowideall "kubectl get ingress -o=wide --all-namespaces"
abbr -a kgcmowideall "kubectl get configmap -o=wide --all-namespaces"
abbr -a kgsecowideall "kubectl get secret -o=wide --all-namespaces"
abbr -a kgnsowideall "kubectl get namespaces -o=wide --all-namespaces"
abbr -a kgojsonall "kubectl get -o=json --all-namespaces"
abbr -a kgpoojsonall "kubectl get pods -o=json --all-namespaces"
abbr -a kgdepojsonall "kubectl get deployment -o=json --all-namespaces"
abbr -a kgstsojsonall "kubectl get statefulset -o=json --all-namespaces"
abbr -a kgsvcojsonall "kubectl get service -o=json --all-namespaces"
abbr -a kgingojsonall "kubectl get ingress -o=json --all-namespaces"
abbr -a kgcmojsonall "kubectl get configmap -o=json --all-namespaces"
abbr -a kgsecojsonall "kubectl get secret -o=json --all-namespaces"
abbr -a kgnsojsonall "kubectl get namespaces -o=json --all-namespaces"
abbr -a kgslall "kubectl get --show-labels --all-namespaces"
abbr -a kgposlall "kubectl get pods --show-labels --all-namespaces"
abbr -a kgdepslall "kubectl get deployment --show-labels --all-namespaces"
abbr -a kgwall "kubectl get --watch --all-namespaces"
abbr -a kgpowall "kubectl get pods --watch --all-namespaces"
abbr -a kgdepwall "kubectl get deployment --watch --all-namespaces"
abbr -a kgstswall "kubectl get statefulset --watch --all-namespaces"
abbr -a kgsvcwall "kubectl get service --watch --all-namespaces"
abbr -a kgingwall "kubectl get ingress --watch --all-namespaces"
abbr -a kgcmwall "kubectl get configmap --watch --all-namespaces"
abbr -a kgsecwall "kubectl get secret --watch --all-namespaces"
abbr -a kgnswall "kubectl get namespaces --watch --all-namespaces"
abbr -a kgf "kubectl get --recursive -f"
abbr -a kdf "kubectl describe --recursive -f"
abbr -a krmf "kubectl delete --recursive -f"
abbr -a kgoyamlf "kubectl get -o=yaml --recursive -f"
abbr -a kgowidef "kubectl get -o=wide --recursive -f"
abbr -a kgojsonf "kubectl get -o=json --recursive -f"
abbr -a kgslf "kubectl get --show-labels --recursive -f"
abbr -a kgwf "kubectl get --watch --recursive -f"
abbr -a kgl "kubectl get -l"
abbr -a ksysgl "kubectl --namespace=kube-system get -l"
abbr -a kdl "kubectl describe -l"
abbr -a ksysdl "kubectl --namespace=kube-system describe -l"
abbr -a krml "kubectl delete -l"
abbr -a ksysrml "kubectl --namespace=kube-system delete -l"
abbr -a kgpol "kubectl get pods -l"
abbr -a ksysgpol "kubectl --namespace=kube-system get pods -l"
abbr -a kdpol "kubectl describe pods -l"
abbr -a ksysdpol "kubectl --namespace=kube-system describe pods -l"
abbr -a krmpol "kubectl delete pods -l"
abbr -a ksysrmpol "kubectl --namespace=kube-system delete pods -l"
abbr -a kgdepl "kubectl get deployment -l"
abbr -a ksysgdepl "kubectl --namespace=kube-system get deployment -l"
abbr -a kddepl "kubectl describe deployment -l"
abbr -a ksysddepl "kubectl --namespace=kube-system describe deployment -l"
abbr -a krmdepl "kubectl delete deployment -l"
abbr -a ksysrmdepl "kubectl --namespace=kube-system delete deployment -l"
abbr -a kgstsl "kubectl get statefulset -l"
abbr -a ksysgstsl "kubectl --namespace=kube-system get statefulset -l"
abbr -a kdstsl "kubectl describe statefulset -l"
abbr -a ksysdstsl "kubectl --namespace=kube-system describe statefulset -l"
abbr -a krmstsl "kubectl delete statefulset -l"
abbr -a ksysrmstsl "kubectl --namespace=kube-system delete statefulset -l"
abbr -a kgsvcl "kubectl get service -l"
abbr -a ksysgsvcl "kubectl --namespace=kube-system get service -l"
abbr -a kdsvcl "kubectl describe service -l"
abbr -a ksysdsvcl "kubectl --namespace=kube-system describe service -l"
abbr -a krmsvcl "kubectl delete service -l"
abbr -a ksysrmsvcl "kubectl --namespace=kube-system delete service -l"
abbr -a kgingl "kubectl get ingress -l"
abbr -a ksysgingl "kubectl --namespace=kube-system get ingress -l"
abbr -a kdingl "kubectl describe ingress -l"
abbr -a ksysdingl "kubectl --namespace=kube-system describe ingress -l"
abbr -a krmingl "kubectl delete ingress -l"
abbr -a ksysrmingl "kubectl --namespace=kube-system delete ingress -l"
abbr -a kgcml "kubectl get configmap -l"
abbr -a ksysgcml "kubectl --namespace=kube-system get configmap -l"
abbr -a kdcml "kubectl describe configmap -l"
abbr -a ksysdcml "kubectl --namespace=kube-system describe configmap -l"
abbr -a krmcml "kubectl delete configmap -l"
abbr -a ksysrmcml "kubectl --namespace=kube-system delete configmap -l"
abbr -a kgsecl "kubectl get secret -l"
abbr -a ksysgsecl "kubectl --namespace=kube-system get secret -l"
abbr -a kdsecl "kubectl describe secret -l"
abbr -a ksysdsecl "kubectl --namespace=kube-system describe secret -l"
abbr -a krmsecl "kubectl delete secret -l"
abbr -a ksysrmsecl "kubectl --namespace=kube-system delete secret -l"
abbr -a kgnol "kubectl get nodes -l"
abbr -a kdnol "kubectl describe nodes -l"
abbr -a kgnsl "kubectl get namespaces -l"
abbr -a kdnsl "kubectl describe namespaces -l"
abbr -a krmnsl "kubectl delete namespaces -l"
abbr -a kgoyamll "kubectl get -o=yaml -l"
abbr -a ksysgoyamll "kubectl --namespace=kube-system get -o=yaml -l"
abbr -a kgpooyamll "kubectl get pods -o=yaml -l"
abbr -a ksysgpooyamll "kubectl --namespace=kube-system get pods -o=yaml -l"
abbr -a kgdepoyamll "kubectl get deployment -o=yaml -l"
abbr -a ksysgdepoyamll "kubectl --namespace=kube-system get deployment -o=yaml -l"
abbr -a kgstsoyamll "kubectl get statefulset -o=yaml -l"
abbr -a ksysgstsoyamll "kubectl --namespace=kube-system get statefulset -o=yaml -l"
abbr -a kgsvcoyamll "kubectl get service -o=yaml -l"
abbr -a ksysgsvcoyamll "kubectl --namespace=kube-system get service -o=yaml -l"
abbr -a kgingoyamll "kubectl get ingress -o=yaml -l"
abbr -a ksysgingoyamll "kubectl --namespace=kube-system get ingress -o=yaml -l"
abbr -a kgcmoyamll "kubectl get configmap -o=yaml -l"
abbr -a ksysgcmoyamll "kubectl --namespace=kube-system get configmap -o=yaml -l"
abbr -a kgsecoyamll "kubectl get secret -o=yaml -l"
abbr -a ksysgsecoyamll "kubectl --namespace=kube-system get secret -o=yaml -l"
abbr -a kgnooyamll "kubectl get nodes -o=yaml -l"
abbr -a kgnsoyamll "kubectl get namespaces -o=yaml -l"
abbr -a kgowidel "kubectl get -o=wide -l"
abbr -a ksysgowidel "kubectl --namespace=kube-system get -o=wide -l"
abbr -a kgpoowidel "kubectl get pods -o=wide -l"
abbr -a ksysgpoowidel "kubectl --namespace=kube-system get pods -o=wide -l"
abbr -a kgdepowidel "kubectl get deployment -o=wide -l"
abbr -a ksysgdepowidel "kubectl --namespace=kube-system get deployment -o=wide -l"
abbr -a kgstsowidel "kubectl get statefulset -o=wide -l"
abbr -a ksysgstsowidel "kubectl --namespace=kube-system get statefulset -o=wide -l"
abbr -a kgsvcowidel "kubectl get service -o=wide -l"
abbr -a ksysgsvcowidel "kubectl --namespace=kube-system get service -o=wide -l"
abbr -a kgingowidel "kubectl get ingress -o=wide -l"
abbr -a ksysgingowidel "kubectl --namespace=kube-system get ingress -o=wide -l"
abbr -a kgcmowidel "kubectl get configmap -o=wide -l"
abbr -a ksysgcmowidel "kubectl --namespace=kube-system get configmap -o=wide -l"
abbr -a kgsecowidel "kubectl get secret -o=wide -l"
abbr -a ksysgsecowidel "kubectl --namespace=kube-system get secret -o=wide -l"
abbr -a kgnoowidel "kubectl get nodes -o=wide -l"
abbr -a kgnsowidel "kubectl get namespaces -o=wide -l"
abbr -a kgojsonl "kubectl get -o=json -l"
abbr -a ksysgojsonl "kubectl --namespace=kube-system get -o=json -l"
abbr -a kgpoojsonl "kubectl get pods -o=json -l"
abbr -a ksysgpoojsonl "kubectl --namespace=kube-system get pods -o=json -l"
abbr -a kgdepojsonl "kubectl get deployment -o=json -l"
abbr -a ksysgdepojsonl "kubectl --namespace=kube-system get deployment -o=json -l"
abbr -a kgstsojsonl "kubectl get statefulset -o=json -l"
abbr -a ksysgstsojsonl "kubectl --namespace=kube-system get statefulset -o=json -l"
abbr -a kgsvcojsonl "kubectl get service -o=json -l"
abbr -a ksysgsvcojsonl "kubectl --namespace=kube-system get service -o=json -l"
abbr -a kgingojsonl "kubectl get ingress -o=json -l"
abbr -a ksysgingojsonl "kubectl --namespace=kube-system get ingress -o=json -l"
abbr -a kgcmojsonl "kubectl get configmap -o=json -l"
abbr -a ksysgcmojsonl "kubectl --namespace=kube-system get configmap -o=json -l"
abbr -a kgsecojsonl "kubectl get secret -o=json -l"
abbr -a ksysgsecojsonl "kubectl --namespace=kube-system get secret -o=json -l"
abbr -a kgnoojsonl "kubectl get nodes -o=json -l"
abbr -a kgnsojsonl "kubectl get namespaces -o=json -l"
abbr -a kgsll "kubectl get --show-labels -l"
abbr -a ksysgsll "kubectl --namespace=kube-system get --show-labels -l"
abbr -a kgposll "kubectl get pods --show-labels -l"
abbr -a ksysgposll "kubectl --namespace=kube-system get pods --show-labels -l"
abbr -a kgdepsll "kubectl get deployment --show-labels -l"
abbr -a ksysgdepsll "kubectl --namespace=kube-system get deployment --show-labels -l"
abbr -a kgwl "kubectl get --watch -l"
abbr -a ksysgwl "kubectl --namespace=kube-system get --watch -l"
abbr -a kgpowl "kubectl get pods --watch -l"
abbr -a ksysgpowl "kubectl --namespace=kube-system get pods --watch -l"
abbr -a kgdepwl "kubectl get deployment --watch -l"
abbr -a ksysgdepwl "kubectl --namespace=kube-system get deployment --watch -l"
abbr -a kgstswl "kubectl get statefulset --watch -l"
abbr -a ksysgstswl "kubectl --namespace=kube-system get statefulset --watch -l"
abbr -a kgsvcwl "kubectl get service --watch -l"
abbr -a ksysgsvcwl "kubectl --namespace=kube-system get service --watch -l"
abbr -a kgingwl "kubectl get ingress --watch -l"
abbr -a ksysgingwl "kubectl --namespace=kube-system get ingress --watch -l"
abbr -a kgcmwl "kubectl get configmap --watch -l"
abbr -a ksysgcmwl "kubectl --namespace=kube-system get configmap --watch -l"
abbr -a kgsecwl "kubectl get secret --watch -l"
abbr -a ksysgsecwl "kubectl --namespace=kube-system get secret --watch -l"
abbr -a kgnowl "kubectl get nodes --watch -l"
abbr -a kgnswl "kubectl get namespaces --watch -l"
abbr -a kgalll "kubectl get --all-namespaces -l"
abbr -a kdalll "kubectl describe --all-namespaces -l"
abbr -a kgpoalll "kubectl get pods --all-namespaces -l"
abbr -a kdpoalll "kubectl describe pods --all-namespaces -l"
abbr -a kgdepalll "kubectl get deployment --all-namespaces -l"
abbr -a kddepalll "kubectl describe deployment --all-namespaces -l"
abbr -a kgstsalll "kubectl get statefulset --all-namespaces -l"
abbr -a kdstsalll "kubectl describe statefulset --all-namespaces -l"
abbr -a kgsvcalll "kubectl get service --all-namespaces -l"
abbr -a kdsvcalll "kubectl describe service --all-namespaces -l"
abbr -a kgingalll "kubectl get ingress --all-namespaces -l"
abbr -a kdingalll "kubectl describe ingress --all-namespaces -l"
abbr -a kgcmalll "kubectl get configmap --all-namespaces -l"
abbr -a kdcmalll "kubectl describe configmap --all-namespaces -l"
abbr -a kgsecalll "kubectl get secret --all-namespaces -l"
abbr -a kdsecalll "kubectl describe secret --all-namespaces -l"
abbr -a kgnsalll "kubectl get namespaces --all-namespaces -l"
abbr -a kdnsalll "kubectl describe namespaces --all-namespaces -l"
abbr -a kgoyamlalll "kubectl get -o=yaml --all-namespaces -l"
abbr -a kgpooyamlalll "kubectl get pods -o=yaml --all-namespaces -l"
abbr -a kgdepoyamlalll "kubectl get deployment -o=yaml --all-namespaces -l"
abbr -a kgstsoyamlalll "kubectl get statefulset -o=yaml --all-namespaces -l"
abbr -a kgsvcoyamlalll "kubectl get service -o=yaml --all-namespaces -l"
abbr -a kgingoyamlalll "kubectl get ingress -o=yaml --all-namespaces -l"
abbr -a kgcmoyamlalll "kubectl get configmap -o=yaml --all-namespaces -l"
abbr -a kgsecoyamlalll "kubectl get secret -o=yaml --all-namespaces -l"
abbr -a kgnsoyamlalll "kubectl get namespaces -o=yaml --all-namespaces -l"
abbr -a kgowidealll "kubectl get -o=wide --all-namespaces -l"
abbr -a kgpoowidealll "kubectl get pods -o=wide --all-namespaces -l"
abbr -a kgdepowidealll "kubectl get deployment -o=wide --all-namespaces -l"
abbr -a kgstsowidealll "kubectl get statefulset -o=wide --all-namespaces -l"
abbr -a kgsvcowidealll "kubectl get service -o=wide --all-namespaces -l"
abbr -a kgingowidealll "kubectl get ingress -o=wide --all-namespaces -l"
abbr -a kgcmowidealll "kubectl get configmap -o=wide --all-namespaces -l"
abbr -a kgsecowidealll "kubectl get secret -o=wide --all-namespaces -l"
abbr -a kgnsowidealll "kubectl get namespaces -o=wide --all-namespaces -l"
abbr -a kgojsonalll "kubectl get -o=json --all-namespaces -l"
abbr -a kgpoojsonalll "kubectl get pods -o=json --all-namespaces -l"
abbr -a kgdepojsonalll "kubectl get deployment -o=json --all-namespaces -l"
abbr -a kgstsojsonalll "kubectl get statefulset -o=json --all-namespaces -l"
abbr -a kgsvcojsonalll "kubectl get service -o=json --all-namespaces -l"
abbr -a kgingojsonalll "kubectl get ingress -o=json --all-namespaces -l"
abbr -a kgcmojsonalll "kubectl get configmap -o=json --all-namespaces -l"
abbr -a kgsecojsonalll "kubectl get secret -o=json --all-namespaces -l"
abbr -a kgnsojsonalll "kubectl get namespaces -o=json --all-namespaces -l"
abbr -a kgslalll "kubectl get --show-labels --all-namespaces -l"
abbr -a kgposlalll "kubectl get pods --show-labels --all-namespaces -l"
abbr -a kgdepslalll "kubectl get deployment --show-labels --all-namespaces -l"
abbr -a kgwalll "kubectl get --watch --all-namespaces -l"
abbr -a kgpowalll "kubectl get pods --watch --all-namespaces -l"
abbr -a kgdepwalll "kubectl get deployment --watch --all-namespaces -l"
abbr -a kgstswalll "kubectl get statefulset --watch --all-namespaces -l"
abbr -a kgsvcwalll "kubectl get service --watch --all-namespaces -l"
abbr -a kgingwalll "kubectl get ingress --watch --all-namespaces -l"
abbr -a kgcmwalll "kubectl get configmap --watch --all-namespaces -l"
abbr -a kgsecwalll "kubectl get secret --watch --all-namespaces -l"
abbr -a kgnswalll "kubectl get namespaces --watch --all-namespaces -l"
abbr -a kgoyamllf "kubectl get -o=yaml -l --recursive -f"
abbr -a kgowidef "kubectl get -o=wide --recursive -f"
abbr -a kgowidefol "kubectl get -o=wide -l --recursive -f"
abbr -a kgojsonlf "kubectl get -o=json -l --recursive -f"
abbr -a kgsllf "kubectl get --show-labels -l --recursive -f"
abbr -a kgwlf "kubectl get --watch -l --recursive -f"
abbr -a kgexec "kubectl get exec"
abbr -a kcluster "kubectl cluster-info"
abbr -a kversion "kubectl version"
abbr -a kapiresources "kubectl api-resources"
abbr -a kapi "kubectl api-versions"
abbr -a kcs "kubectl config get-contexts"
abbr -a kcsc "kubectl config current-context"
abbr -a kcuc "kubectl config use-context"
abbr -a kcgc "kubectl config get-contexts"
abbr -a kns "kubectl config set-context --current --namespace"
abbr -a ktop "kubectl top"
abbr -a ktoppo "kubectl top pod"
abbr -a ktopno "kubectl top node"
abbr -a krollout "kubectl rollout"
abbr -a krollouts "kubectl rollout status"
abbr -a krollouta "kubectl rollout history"
abbr -a krolloutr "kubectl rollout restart"
abbr -a krolloutp "kubectl rollout pause"
abbr -a krolloutre "kubectl rollout resume"
abbr -a krolloutu "kubectl rollout undo"

# Mark as installed
set -U _kubectl_abbr_installed 1

echo "Done! Kubectl abbreviations have been installed as universal variables."
echo "They will persist across all Fish sessions without redefining on startup."
