format = """
[╭╴](fg:arrow)\
$directory\
$git_branch\
$git_status \
$azure\
$aws \
$kubernetes\
$terraform\
$python\
$cmd_duration\
$line_break\
[╰─](fg:arrow)$character\
"""

[directory]
style = "bold blue"
truncation_length = 3
truncate_to_repo = true
truncation_symbol = "…/"
read_only ="  "

[git_branch]
symbol = "git:"
truncation_symbol = "…"
truncation_length = 20
style = "#FF8C00 bold"

[git_status]
format = "([$staged](green bold)[$deleted](red bold)[$modified](yellow bold)[$renamed](blue bold)[$ahead_behind]($style))"
ahead = "⇡${count}"
behind = "⇣${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
modified = "!${count}"
staged = "+${count}"
renamed = "»${count}"
deleted = "-${count}"
style = "bold red"

[azure]
format = "[$symbol](blue bold)[$subscription]($style) "
symbol = "az:"
style = "white bold"
disabled = false

[azure.subscription_aliases]
s165-teachingqualificationsservice-development = "s165-dev"
s165-teachingqualificationsservice-test = "s165-test"
s165-teachingqualificationsservice-production = "s165-prod"
s189-teacher-services-cloud-development = "s189-dev"
s189-teacher-services-cloud-test = "s189-test"
s189-teacher-services-cloud-production = "s189-prod"

[kubernetes]
format = '[$symbol$context(\($namespace\))]($style) '
symbol = "k8s:"
style = "cyan bold"
disabled = false

[cmd_duration]
min_time = 500
format = "[$duration]($style) "

[character]
success_symbol = "[➜](bold green)"
error_symbol = "[➜](bold red)"

[terraform]
format = "[$symbol(tf:$version)]($style) "
symbol = "tf:"
style = "bold 105"
disabled = false

[python]
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'
symbol = "py:"
pyenv_version_name = true
pyenv_prefix = "pyenv "
style = "purple bold"

[aws]
format = "[(\\[$symbol$profile(@$region):$duration\\])]($style)"
symbol = "aws:"
style = "bold yellow"
force_display = true

[aws.region_aliases]
us-west-2    = "usw2"
us-west-1    = "usw1"
us-east-2    = "use2"
us-east-1    = "use1"
ca-central-1 = "ca"
eu-west-1    = "euw1"
eu-central-1 = "euc1"

[aws.profile_aliases]
petlab = "LABS"
security = "SEC"
management = "MGT"
prod = "PROD"
logging = "LOG"
