#!/usr/bin/env bash
# db-sandbox.sh — Per-project database sidecars for agent testing

set -euo pipefail

DOTFILES_ROOT="${DOTFILES_ROOT:-${HOME}/dotfiles}"
PORT_ALLOCATOR="${DOTFILES_ROOT}/scripts/port-allocator.sh"
STATE_ROOT="${DB_SANDBOX_STATE_ROOT:-${HOME}/.claude/db-sandbox}"
DEFAULT_ENGINES="postgres,redis"
POSTGRES_IMAGE="${DB_SANDBOX_POSTGRES_IMAGE:-postgres:16-alpine}"
REDIS_IMAGE="${DB_SANDBOX_REDIS_IMAGE:-redis:7-alpine}"
MYSQL_IMAGE="${DB_SANDBOX_MYSQL_IMAGE:-mysql:8}"
POSTGRES_USER="${DB_SANDBOX_POSTGRES_USER:-postgres}"
POSTGRES_PASSWORD="${DB_SANDBOX_POSTGRES_PASSWORD:-postgres}"
POSTGRES_DB="${DB_SANDBOX_POSTGRES_DB:-app}"
MYSQL_USER="${DB_SANDBOX_MYSQL_USER:-mysql}"
MYSQL_PASSWORD="${DB_SANDBOX_MYSQL_PASSWORD:-mysql}"
MYSQL_DATABASE="${DB_SANDBOX_MYSQL_DATABASE:-app}"
MYSQL_ROOT_PASSWORD="${DB_SANDBOX_MYSQL_ROOT_PASSWORD:-mysqlroot}"

usage() {
    cat <<'EOF'
Usage: db-sandbox.sh <command> [args]

Commands:
  up [engines]        Start compose DB services or own sidecars
  down [--volumes]    Stop the sandbox, optionally removing volumes
  status              Show current context and containers
  list                List known sandbox contexts
  logs <engine>       Tail logs for postgres, redis, or mysql
  env                 Print connection env vars from .env.db
  context             Print the derived sandbox context name
  prune               Remove sandboxes whose project directory is gone

Engines are comma-separated: postgres,redis,mysql. Defaults to postgres,redis.
Set DB_SANDBOX_NAME to override the context name.
Set DB_SANDBOX_CWD to derive the context from a directory other than $PWD.
EOF
}

die() {
    echo "Error: $*" >&2
    exit 1
}

require_command() {
    command -v "$1" >/dev/null 2>&1 || die "required command not found: $1"
}

project_root() {
    local cwd="${DB_SANDBOX_CWD:-$PWD}"
    git -C "$cwd" rev-parse --show-toplevel 2>/dev/null || printf '%s\n' "$cwd"
}

sanitize_name() {
    local raw="$1"
    raw=$(basename "$raw")
    printf '%s\n' "$raw" | tr '[:upper:]' '[:lower:]' | sed -E 's/[^a-z0-9_.-]+/-/g; s/^-+//; s/-+$//' | cut -c1-48
}

context_name() {
    if [ -n "${DB_SANDBOX_NAME:-}" ]; then
        sanitize_name "$DB_SANDBOX_NAME"
    else
        sanitize_name "$(project_root)"
    fi
}

state_dir() {
    printf '%s/%s\n' "$STATE_ROOT" "$(context_name)"
}

compose_project() {
    printf 'dbsbx-%s\n' "$(context_name)"
}

find_compose_file() {
    local root="$1"
    local candidate
    for candidate in docker-compose.yml docker-compose.yaml compose.yml compose.yaml; do
        if [ -f "$root/$candidate" ]; then
            printf '%s/%s\n' "$root" "$candidate"
            return 0
        fi
    done
    return 1
}

normalize_engines() {
    local engines="${1:-}"
    if [ -z "$engines" ]; then
        engines="${DB_SANDBOX:-$DEFAULT_ENGINES}"
    fi
    printf '%s\n' "$engines" | tr ',' '\n' | tr '[:upper:]' '[:lower:]' | awk 'NF { gsub(/^[[:space:]]+|[[:space:]]+$/, ""); print }'
}

engine_enabled() {
    local wanted="$1"
    local engine
    shift || true
    for engine in "$@"; do
        [ "$engine" = "$wanted" ] && return 0
    done
    return 1
}

allocate_ports() {
    require_command jq
    [ -x "$PORT_ALLOCATOR" ] || die "port allocator not found at $PORT_ALLOCATOR"
    "$PORT_ALLOCATOR" allocate "$(context_name)" >/dev/null
    "$PORT_ALLOCATOR" env "$(context_name)"
}

port_value() {
    local name="$1"
    local ports="$2"
    printf '%s\n' "$ports" | awk -F= -v key="$name" '$1 == key { print $2; exit }'
}

write_project_metadata() {
    local dir="$1"
    mkdir -p "$dir"
    project_root >"$dir/project-dir"
}

write_env_file() {
    local dir="$1"
    local ports="$2"
    local mode="$3"
    local postgres_port redis_port mysql_port
    postgres_port=$(port_value PORT_DB "$ports")
    redis_port=$(port_value PORT_REDIS "$ports")
    mysql_port=$(port_value PORT_SPARE_1 "$ports")

    cat >"$dir/.env.db" <<EOF
# Generated by db-sandbox.sh for context $(context_name)
DB_SANDBOX_CONTEXT=$(context_name)
DB_SANDBOX_MODE=$mode
DB_HOST=127.0.0.1
DB_PORT=$postgres_port
DATABASE_URL=postgresql://$POSTGRES_USER:$POSTGRES_PASSWORD@127.0.0.1:$postgres_port/$POSTGRES_DB
POSTGRES_HOST=127.0.0.1
POSTGRES_PORT=$postgres_port
POSTGRES_USER=$POSTGRES_USER
POSTGRES_PASSWORD=$POSTGRES_PASSWORD
POSTGRES_DB=$POSTGRES_DB
POSTGRES_URL=postgresql://$POSTGRES_USER:$POSTGRES_PASSWORD@127.0.0.1:$postgres_port/$POSTGRES_DB
REDIS_HOST=127.0.0.1
REDIS_PORT=$redis_port
REDIS_URL=redis://127.0.0.1:$redis_port/0
MYSQL_HOST=127.0.0.1
MYSQL_PORT=$mysql_port
MYSQL_USER=$MYSQL_USER
MYSQL_PASSWORD=$MYSQL_PASSWORD
MYSQL_DATABASE=$MYSQL_DATABASE
MYSQL_URL=mysql://$MYSQL_USER:$MYSQL_PASSWORD@127.0.0.1:$mysql_port/$MYSQL_DATABASE
EOF
}

compose_services() {
    local compose_file="$1"
    shift || true
    local engines=("$@")
    require_command docker
    require_command jq

    docker compose -f "$compose_file" config --format json | jq -r --argjson engines "$(printf '%s\n' "${engines[@]}" | jq -R . | jq -s .)" '
      .services
      | to_entries[]
      | .key as $name
      | ((.value.image // "") | ascii_downcase) as $image
      | if (($engines | index("postgres")) and ($image | test("postgres"))) then "postgres\t" + $name
        elif (($engines | index("redis")) and ($image | test("redis"))) then "redis\t" + $name
        elif (($engines | index("mysql")) and ($image | test("mysql|mariadb"))) then "mysql\t" + $name
        else empty end
    '
}

write_compose_override() {
    local dir="$1"
    local ports="$2"
    local services="$3"
    local override="$dir/compose.override.yml"
    local postgres_port redis_port mysql_port
    postgres_port=$(port_value PORT_DB "$ports")
    redis_port=$(port_value PORT_REDIS "$ports")
    mysql_port=$(port_value PORT_SPARE_1 "$ports")

    {
        echo "services:"
        while IFS=$'\t' read -r engine service; do
            [ -z "${engine:-}" ] && continue
            echo "  $service:"
            echo "    ports:"
            case "$engine" in
            postgres) echo "      - \"127.0.0.1:${postgres_port}:5432\"" ;;
            redis) echo "      - \"127.0.0.1:${redis_port}:6379\"" ;;
            mysql) echo "      - \"127.0.0.1:${mysql_port}:3306\"" ;;
            esac
        done <<<"$services"
    } >"$override"
}

cmd_up() {
    require_command docker
    local dir root compose_file ports engines service_rows services
    dir=$(state_dir)
    root=$(project_root)
    engines=()
    while IFS= read -r engine; do
        engines+=("$engine")
    done < <(normalize_engines "${1:-}")
    [ ${#engines[@]} -gt 0 ] || die "no engines requested"

    mkdir -p "$dir"
    write_project_metadata "$dir"
    ports=$(allocate_ports)

    if compose_file=$(find_compose_file "$root"); then
        service_rows=$(compose_services "$compose_file" "${engines[@]}")
        if [ -n "$service_rows" ]; then
            write_compose_override "$dir" "$ports" "$service_rows"
            services=$(printf '%s\n' "$service_rows" | awk -F'\t' '{print $2}')
            docker compose -p "$(compose_project)" -f "$compose_file" -f "$dir/compose.override.yml" up -d $services
            echo compose >"$dir/mode"
            printf '%s\n' "$compose_file" >"$dir/compose-file"
            write_env_file "$dir" "$ports" compose
            echo "DB sandbox up: $(context_name) (compose)"
            return 0
        fi
    fi

    docker network inspect "$(compose_project)" >/dev/null 2>&1 || docker network create "$(compose_project)" >/dev/null
    for engine in "${engines[@]}"; do
        case "$engine" in
        postgres)
            docker rm -f "$(compose_project)-postgres" >/dev/null 2>&1 || true
            docker run -d --name "$(compose_project)-postgres" --network "$(compose_project)" \
                --label "db-sandbox.context=$(context_name)" --label "db-sandbox.engine=postgres" --label "gwt.instance=$(context_name)" \
                -e POSTGRES_USER="$POSTGRES_USER" -e POSTGRES_PASSWORD="$POSTGRES_PASSWORD" -e POSTGRES_DB="$POSTGRES_DB" \
                -p "127.0.0.1:$(port_value PORT_DB "$ports"):5432" -v "$(compose_project)-postgres:/var/lib/postgresql/data" \
                "$POSTGRES_IMAGE" >/dev/null
            ;;
        redis)
            docker rm -f "$(compose_project)-redis" >/dev/null 2>&1 || true
            docker run -d --name "$(compose_project)-redis" --network "$(compose_project)" \
                --label "db-sandbox.context=$(context_name)" --label "db-sandbox.engine=redis" --label "gwt.instance=$(context_name)" \
                -p "127.0.0.1:$(port_value PORT_REDIS "$ports"):6379" -v "$(compose_project)-redis:/data" \
                "$REDIS_IMAGE" >/dev/null
            ;;
        mysql | mariadb)
            docker rm -f "$(compose_project)-mysql" >/dev/null 2>&1 || true
            docker run -d --name "$(compose_project)-mysql" --network "$(compose_project)" \
                --label "db-sandbox.context=$(context_name)" --label "db-sandbox.engine=mysql" --label "gwt.instance=$(context_name)" \
                -e MYSQL_ROOT_PASSWORD="$MYSQL_ROOT_PASSWORD" -e MYSQL_USER="$MYSQL_USER" -e MYSQL_PASSWORD="$MYSQL_PASSWORD" -e MYSQL_DATABASE="$MYSQL_DATABASE" \
                -p "127.0.0.1:$(port_value PORT_SPARE_1 "$ports"):3306" -v "$(compose_project)-mysql:/var/lib/mysql" \
                "$MYSQL_IMAGE" >/dev/null
            ;;
        *)
            die "unsupported engine: $engine"
            ;;
        esac
    done

    echo own >"$dir/mode"
    write_env_file "$dir" "$ports" own
    echo "DB sandbox up: $(context_name) (own: ${engines[*]})"
}

cmd_down() {
    require_command docker
    local remove_volumes=false
    if [ "${1:-}" = "--volumes" ]; then
        remove_volumes=true
    fi
    local dir mode compose_file
    dir=$(state_dir)
    mode=$(cat "$dir/mode" 2>/dev/null || true)

    if [ "$mode" = "compose" ]; then
        compose_file=$(cat "$dir/compose-file" 2>/dev/null || true)
        if [ -n "$compose_file" ] && [ -f "$compose_file" ]; then
            if $remove_volumes; then
                docker compose -p "$(compose_project)" -f "$compose_file" -f "$dir/compose.override.yml" down --volumes
            else
                docker compose -p "$(compose_project)" -f "$compose_file" -f "$dir/compose.override.yml" down
            fi
        fi
    else
        local container_id
        while IFS= read -r container_id; do
            [ -n "$container_id" ] || continue
            docker rm -f "$container_id" >/dev/null
        done < <(docker ps -a --filter "label=db-sandbox.context=$(context_name)" --format '{{.ID}}')
        docker network rm "$(compose_project)" >/dev/null 2>&1 || true
        if $remove_volumes; then
            local volume_name
            while IFS= read -r volume_name; do
                [ -n "$volume_name" ] || continue
                docker volume rm "$volume_name" >/dev/null
            done < <(docker volume ls --filter "name=$(compose_project)-" --format '{{.Name}}')
        fi
    fi

    if $remove_volumes; then
        "$PORT_ALLOCATOR" release "$(context_name)" >/dev/null 2>&1 || true
        rm -rf "$dir"
    fi
    echo "DB sandbox down: $(context_name)"
}

cmd_status() {
    local dir
    dir=$(state_dir)
    echo "context: $(context_name)"
    echo "state: $dir"
    [ -f "$dir/.env.db" ] && echo "env: $dir/.env.db"
    if command -v docker >/dev/null 2>&1; then
        docker ps -a --filter "label=db-sandbox.context=$(context_name)" --format 'table {{.Names}}\t{{.Status}}\t{{.Ports}}'
        if [ "$(cat "$dir/mode" 2>/dev/null || true)" = "compose" ]; then
            docker compose -p "$(compose_project)" ps 2>/dev/null || true
        fi
    fi
}

cmd_list() {
    mkdir -p "$STATE_ROOT"
    printf 'CONTEXT\tMODE\tPROJECT\n'
    for dir in "$STATE_ROOT"/*; do
        [ -d "$dir" ] || continue
        printf '%s\t%s\t%s\n' "$(basename "$dir")" "$(cat "$dir/mode" 2>/dev/null || echo unknown)" "$(cat "$dir/project-dir" 2>/dev/null || echo unknown)"
    done | column -t -s $'\t'
}

cmd_logs() {
    require_command docker
    local engine="${1:-}"
    [ -n "$engine" ] || die "logs requires an engine"
    if [ "$(cat "$(state_dir)/mode" 2>/dev/null || true)" = "compose" ]; then
        local compose_file service
        compose_file=$(cat "$(state_dir)/compose-file" 2>/dev/null || true)
        service=$(compose_services "$compose_file" "$engine" | awk -F'\t' 'NR == 1 { print $2 }')
        [ -n "$service" ] || die "no compose service found for $engine"
        docker compose -p "$(compose_project)" -f "$compose_file" -f "$(state_dir)/compose.override.yml" logs -f "$service"
    else
        docker logs -f "$(compose_project)-$engine"
    fi
}

cmd_env() {
    local env_file
    env_file="$(state_dir)/.env.db"
    [ -f "$env_file" ] || die "no env file found for $(context_name); run: db up"
    cat "$env_file"
}

cmd_prune() {
    require_command docker
    mkdir -p "$STATE_ROOT"
    local dir project context removed=0
    for dir in "$STATE_ROOT"/*; do
        [ -d "$dir" ] || continue
        project=$(cat "$dir/project-dir" 2>/dev/null || true)
        [ -n "$project" ] || continue
        [ -e "$project" ] && continue
        context=$(basename "$dir")
        DB_SANDBOX_NAME="$context" cmd_down --volumes >/dev/null 2>&1 || true
        echo "Pruned: $context"
        removed=$((removed + 1))
    done
    echo "Pruned $removed DB sandbox(es)"
}

case "${1:-}" in
up)
    shift
    cmd_up "${1:-}"
    ;;
down)
    shift
    cmd_down "${1:-}"
    ;;
status)
    cmd_status
    ;;
list)
    cmd_list
    ;;
logs)
    shift
    cmd_logs "${1:-}"
    ;;
env)
    cmd_env
    ;;
context)
    context_name
    ;;
prune)
    cmd_prune
    ;;
"" | -h | --help | help)
    usage
    ;;
*)
    usage >&2
    exit 1
    ;;
esac
