#!/usr/bin/env bash
# aimux init - interactive first-run setup

_init_force=false

while [[ $# -gt 0 ]]; do
    case "$1" in
    --force | -f)
        _init_force=true
        shift
        ;;
    -h | --help)
        cat <<'HELP'
Usage: aimux init [--force]

Interactive first-run setup for aimux

Options:
  --force    Overwrite existing config (re-run setup)
  -h, --help Show this help
HELP
        exit 0
        ;;
    *) shift ;;
    esac
done

printf "\n${BOLD}aimux init${RESET} - AI Agent Multiplexer Setup\n"
printf "${DIM}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RESET}\n\n"

# Check for existing config
if [[ -f "$AIMUX_HOME/config.toml" ]] && ! $_init_force; then
    warn "Config already exists: $AIMUX_HOME/config.toml"
    warn "Use --force to overwrite"
    exit 1
fi

# --- Step 1: Create directory structure ---
info "Creating directory structure..."

dirs=(
    "$AIMUX_HOME"
    "$AIMUX_HOME/state"
    "$AIMUX_HOME/logs"
    "$AIMUX_HOME/providers"
    "$AIMUX_HOME/templates"
    "$AIMUX_HOME/templates/launch"
)

for dir in "${dirs[@]}"; do
    mkdir -p "$dir"
done
printf "  ${GREEN}ok${RESET}  ~/.aimux/ directory structure\n"

# --- Step 2: Detect required tools ---
info "Detecting required tools..."

_ok=0
_warn=0
_missing=0

_check_tool() {
    local name="$1" required="${2:-false}" desc="${3:-}"
    if has "$name"; then
        local ver
        ver=$("$name" --version 2>/dev/null | head -1 || echo "installed")
        printf "  ${GREEN}ok${RESET}  %-15s %s\n" "$name" "${DIM}${ver}${RESET}"
        _ok=$((_ok + 1))
        return 0
    elif [[ "$required" == "true" ]]; then
        printf "  ${RED}missing${RESET}  %-12s %s\n" "$name" "${desc}"
        _missing=$((_missing + 1))
        return 1
    else
        printf "  ${YELLOW}optional${RESET} %-12s %s\n" "$name" "${desc}"
        _warn=$((_warn + 1))
        return 1
    fi
}

_check_tool tmux true "(required) terminal multiplexer"
_check_tool git true "(required) version control"
_check_tool fzf false "(optional) fuzzy finder for pickers"
_check_tool jq false "(optional) JSON processing"
_check_tool gh false "(optional) GitHub CLI for PR workflow"

printf "\n"

# --- Step 3: Detect AI agents ---
info "Detecting AI agents..."

declare -A _detected_providers=()

_check_agent() {
    local name="$1" cmd="$2" desc="$3"
    if has "$cmd"; then
        local ver
        ver=$("$cmd" --version 2>/dev/null | head -1 || echo "installed")
        printf "  ${GREEN}found${RESET}  %-15s %s\n" "$name" "${DIM}${ver}${RESET}"
        _detected_providers["$name"]=1
        return 0
    else
        printf "  ${DIM}not found${RESET}  %-12s %s\n" "$name" "$desc"
        return 1
    fi
}

_check_agent claude claude "Claude Code CLI"
_check_agent codex codex "Codex CLI"
_check_agent ollama ollama "Ollama local models"
_check_agent aider aider "Aider AI pair programming"
_check_agent gemini gemini "Gemini CLI"
_check_agent opencode opencode "OpenCode CLI"
_check_agent cline cline "Cline CLI"
_check_agent amp amp "Amp CLI"
_check_agent cursor cursor "Cursor CLI"

# Check gh copilot separately (subcommand)
if has gh && gh copilot --version &>/dev/null 2>&1; then
    printf "  ${GREEN}found${RESET}  %-15s %s\n" "copilot" "${DIM}via gh copilot${RESET}"
    _detected_providers["copilot"]=1
else
    printf "  ${DIM}not found${RESET}  %-12s %s\n" "copilot" "GitHub Copilot CLI (gh extension)"
fi

printf "\n"

# --- Step 4: Determine default provider ---
default_provider="claude"
if [[ -z "${_detected_providers[claude]:-}" ]]; then
    # Pick the first detected provider as default
    for p in codex ollama aider gemini opencode cline amp cursor copilot; do
        if [[ -n "${_detected_providers[$p]:-}" ]]; then
            default_provider="$p"
            break
        fi
    done
fi

# --- Step 5: Generate config.toml ---
info "Generating config.toml..."

config_file="$AIMUX_HOME/config.toml"

cat >"$config_file" <<EOF
# aimux configuration
# Generated by: aimux init ($(date +%Y-%m-%d))

[general]
poll_interval = 10
stuck_timeout = 300
default_provider = "${default_provider}"

[notifications]
channels = ["bell", "osc", "native"]
webhook_url = ""

[queue]
max_concurrent = 3
cooldown = 60
EOF

# Add detected provider configs
for provider in claude codex ollama aider gemini opencode cline amp cursor copilot; do
    [[ -z "${_detected_providers[$provider]:-}" ]] && continue

    case "$provider" in
    claude)
        cat >>"$config_file" <<'EOF'

[providers.claude]
command = "claude"
args = ["--effort", "max"]
detect_patterns = ["claude"]
working_pattern = "… \\("
done_patterns = ["COMPLETE", "_DONE", "TICKET_TASK_COMPLETE"]
EOF
        ;;
    codex)
        cat >>"$config_file" <<'EOF'

[providers.codex]
command = "codex"
args = ["--full-auto"]
detect_patterns = ["codex"]
working_pattern = ""
done_patterns = ["COMPLETE"]
EOF
        ;;
    ollama)
        cat >>"$config_file" <<'EOF'

[providers.ollama]
command = "ollama"
args = ["run"]
detect_patterns = ["ollama"]
working_pattern = ""
done_patterns = [">>>"]
EOF
        ;;
    aider)
        cat >>"$config_file" <<'EOF'

[providers.aider]
command = "aider"
args = []
detect_patterns = ["aider"]
working_pattern = ""
done_patterns = ["Applied edit", "Commit "]
EOF
        ;;
    gemini)
        cat >>"$config_file" <<'EOF'

[providers.gemini]
command = "gemini"
args = []
detect_patterns = ["gemini"]
working_pattern = "Thinking"
done_patterns = []
EOF
        ;;
    opencode)
        cat >>"$config_file" <<'EOF'

[providers.opencode]
command = "opencode"
args = []
detect_patterns = ["opencode"]
working_pattern = ""
done_patterns = []
EOF
        ;;
    cline)
        cat >>"$config_file" <<'EOF'

[providers.cline]
command = "cline"
args = []
detect_patterns = ["cline"]
working_pattern = ""
done_patterns = []
EOF
        ;;
    amp)
        cat >>"$config_file" <<'EOF'

[providers.amp]
command = "amp"
args = []
detect_patterns = ["amp"]
working_pattern = ""
done_patterns = []
EOF
        ;;
    cursor)
        cat >>"$config_file" <<'EOF'

[providers.cursor]
command = "cursor"
args = []
detect_patterns = ["cursor"]
working_pattern = ""
done_patterns = []
EOF
        ;;
    copilot)
        cat >>"$config_file" <<'EOF'

[providers.copilot]
command = "gh"
args = ["copilot"]
detect_patterns = ["gh"]
working_pattern = ""
done_patterns = []
EOF
        ;;
    esac
done

printf "  ${GREEN}ok${RESET}  %s\n" "$config_file"

# --- Summary ---
printf "\n${DIM}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RESET}\n"
printf "${BOLD}Setup complete${RESET}\n\n"

detected_count="${#_detected_providers[@]}"
printf "  Tools:      %d ok, %d optional missing, %d required missing\n" "$_ok" "$_warn" "$_missing"
printf "  Providers:  %d detected\n" "$detected_count"
printf "  Default:    %s\n" "$default_provider"
printf "  Config:     %s\n" "$config_file"

printf "\n${BOLD}Next steps${RESET}:\n"
printf "  aimux doctor              Check full health status\n"
printf "  aimux new <branch>        Create your first workspace\n"
printf "  aimux run TICKET \"msg\"     Execute a ticket autonomously\n"

if [[ "$_missing" -gt 0 ]]; then
    printf "\n  ${YELLOW}Warning${RESET}: %d required tools missing. Install them before using aimux.\n" "$_missing"
fi

printf "\n"
log "init: setup complete ($detected_count providers detected, default: $default_provider)"
